apps/config/urls.py
from django.urls import path, include
from config import views

urlpatterns = [
    path('', views.painel_view, name='painel'), 
    path('configuracao/', views.configuracao_view, name='configuracao'), 
    path('relatorio/', views.relatorio_view, name='relatorio'),
    path('catalogo/', views.catalogo_view, name='catalogo'),
    path('quadros/', views.quadros_view, name='quadros'),
    path('pagamentos/', include('apps.pagamentos.urls')),
]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('contas.urls')), 
    path('perfil/', include('perfil.urls')), 
    path('config/', include('config.urls')),
    path('forum/', include('forum.urls')),
    #path('catalogo/', include('catalogo.urls')),
    #path('quadros/', include('quadros.urls')),
    path('', include('pages.urls')),
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/config/models.py
from django.db import models
from django.core.exceptions import ValidationError

# Create your models here.
class Logo(models.Model):
    title = models.CharField('Título/Alt', max_length=100)
    image = models.ImageField('Logo', upload_to='images')

    class Meta:
        verbose_name = 'Logo'
        verbose_name_plural = 'Logo'

    def __str__(self):
        return self.title

    def clean(self):
        model = self.__class__
        if model.objects.count() >= 2 and not self.pk:
            raise ValidationError('Já existe uma 2 logomarca cadastrada.')


class SEOHome(models.Model):
    meta_description = models.CharField('Meta descrição', max_length=255)
    meta_keywords = models.CharField('Palavras chaves', max_length=255, help_text='Separadas por virgula')

    class Meta:
        verbose_name = 'SEO Home'
        verbose_name_plural = 'SEO Home'

    def __str__(self) -> str:
        return 'Meta tags da Página Home'

    def clean(self):
        model = self.__class__
        if model.objects.exists() and self.pk != model.objects.first().pk:
            raise ValidationError('Já existe meta tags cadastradas para a Home.')



class GoogleAnalytics(models.Model):
    ga_id = models.CharField('Código GA', max_length=75)

    class Meta:
        verbose_name = 'Google Analytics'
        verbose_name_plural = 'Google Analytics'

    def __str__(self) -> str:
        return 'Código Google Analytics'

    def clean(self) -> None:
        model = self.__class__
        if model.objects.exists() and self.pk != model.objects.first().pk: 
            raise ValidationError('Já existe um Código GA cadastrado.')



class Scripts(models.Model):
    SCRIPT_PLACE = (
        ('HD', 'Head/Cabeçalho'),
        ('FT', 'Footer/Rodapé'),
    )
    name = models.CharField('Nome do Script', max_length=75)
    script = models.TextField('Script', 
					help_text='Adicione o script completo, inclusive com as tags <script></script>.')
    place = models.CharField('Local', max_length=2, choices=SCRIPT_PLACE, help_text='Escolha onde o script deve ser inserido.')
    is_active = models.BooleanField('Ativo?', default=True, 
				help_text='Os scripts inativos deixarão de ser inseridos nas páginas.')

    class Meta:
        verbose_name = 'Script'
        verbose_name_plural = 'Scripts'

    def __str__(self) -> str:
        return self.name

apps/contas/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
import re


# Create your models here.
class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None, **kwargs):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(email=self.normalize_email(email), **kwargs)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **kwargs):
        kwargs.setdefault('is_staff', True)
        kwargs.setdefault('is_superuser', True)
        return self.create_user(email, password, **kwargs)

class MyUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=100,unique=True,null=True)
    email = models.EmailField(unique=True,max_length=255)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField('date joined', auto_now_add=True)
    force_change_password = models.BooleanField(default=False)

    
    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = MyUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'

    def get_short_name(self):
        return self.first_name

    def requires_password_change(self):
        return self.force_change_password

    def save(self, *args, **kwargs):
        get_email = self.email.split("@")[0]
        email = re.sub(r"[^a-zA-Z0-9]","",get_email)
        self.username = email
        super(MyUser, self).save(*args, **kwargs)

apps/config/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def painel_view(request):
    return render(request, 'painel.html')

@login_required
def configuracao_view(request):
    return render(request, 'configuracao.html')

@login_required
def relatorio_view(request):
    return render(request, 'relatorio.html')

@login_required
def catalogo_view(request):
    return render(request, 'dash-lista-catalogo.html')

@login_required
def quadros_view(request):
    return render(request, 'dash-lista-quadros.html')

apps/config/templates/configuracao.html
{% extends 'base_dashboard.html' %}
{% block title %}Configurações{% endblock %}
{% block content_dash %}

<div class="d-flex flex-wrap gap-3">
    <div class="p-5 bg-light" style="width: 430px;">
        <h4>Contas</h4>
        <p>Configurações do aplicativo contas</p>
        <ul>
            <li><a href="{% url 'atualizar_usuario' request.user.username %}">Alterar Configurações da Conta</a></li>
            <li><a href="{% url 'password_change' %}">Alterar minha senha</a></li>
            <li><a href="{% url 'editar-perfil' request.user.username %}">Editar meu Perfil</a></li> 
            {% if perms.contas.view_myuser %}
            <li><a href="{% url 'lista_usuarios' %}">Lista Todos usuários</a></li>
            {% endif %} 
        </ul>
    </div>

    <div class="p-5 bg-light" style="width: 430px;">
        <h4>Sistema</h4>
        <p>Configurações de logo,Banner,informações empresa.</p>
        <ul>
            <li><a href="#">Alterar Informações da empresa</a></li>
            <li><a href="#">Alterar Banner Inicial</a></li>
            <li><a href="#">Tags/Metas/Robot</a></li>
            <li><a href="#">Alterar Logo</a></li>
        </ul>
    </div>

    <div class="p-5 bg-light" style="width: 430px;">
        <h4>Catálogo</h4>
        <p>Configurações de peças, preços.</p>
        <ul>
            <li><a href="#">Incluir produto</a></li>
            <li><a href="#">Alterar banner inicial</a></li>
            <li><a href="#">ALterar imagens</a></li>
            <li><a href="#">Alterar preço</a></li>
        </ul>
    </div>


    <div class="p-5 bg-light" style="width: 430px;">
        <h4>Quadros</h4>
        <p>Configurações dos quadros, preços.</p>
        <ul>
            <li><a href="#">Incluir quadro</a></li>
            <li><a href="#">Alterar banner inicial</a></li>
            <li><a href="#">ALterar imagens</a></li>
            <li><a href="#">Alterar preço</a></li>
        </ul>
    </div>


</div>

{% endblock %}

apps/config/templates/painel.html
{% extends 'base_dashboard.html' %}
{% block title %}Painel{% endblock %}
{% block content_dash %} 
<div class="p-5 bg-light">
	<h4>Bem-Vindo(a), {{user.first_name}} {{user.last_name}}</h4>
	<p>Painel administrativo do usuário.</p>
</div>
{% endblock %}

apps/config/templates/relatorio.html
{% extends 'base_dashboard.html' %}
{% block title %}Relatórios{% endblock %}
{% block content_dash %} 
<div class="row row-cols-1 row-cols-md-3 g-4"> 
	
	<div class="col" style="width: 25rem;">   
		<div class="card h-100 border-0 bg-white shadow-sm">
			<div class="card-body py-5 text-center">
				<h2 class="card-title">Postagens</h2>
				<p class="card-text">Lista de Postagens</p>
			</div>
			<div class="d-grid col-10 mx-auto p-5">  
				<button class="btn btn-info btn-lg w-100" 
					onclick="location.href='{% url 'dash-lista-postagem-forum' %}'">
					Acessar</button> 
			</div>
		</div> 
	</div> 
	
	<!-- Outros -->
	
	<div class="col" style="width: 25rem;">   
		<div class="card h-100 border-0 bg-white shadow-sm">
			<div class="card-body py-5 text-center">
				<h2 class="card-title">Catálogo</h2>
				<p class="card-text">Lista de Produtos</p>
			</div>
			<div class="d-grid col-10 mx-auto p-5">  
				<button class="btn btn-info btn-lg w-100" 
					onclick="location.href='{% url 'catalogo' %}'">
					Acessar</button> 
			</div>
		</div> 
	</div>  


	<div class="col" style="width: 25rem;">   
		<div class="card h-100 border-0 bg-white shadow-sm">
			<div class="card-body py-5 text-center">
				<h2 class="card-title">Quadros</h2>
				<p class="card-text">Lista de Quadros</p>
			</div>
			<div class="d-grid col-10 mx-auto p-5">  
				<button class="btn btn-info btn-lg w-100" 
					onclick="location.href='{% url 'quadros' %}'">
					Acessar</button> 
			</div>
		</div> 
	</div>  

</div>
{% endblock %}